.catalog:
  name: "Portworx"
  version: "1.1.6-2017-02-08-GA"
  description: "Container Defined Storage for Docker"
  uuid: 352669-pwx-1.1.6
  minimum_rancher_version: v0.56.0
  questions:
    - variable: cluster_id
      description: "Arbitrary Cluster ID, common to all nodes in PX cluster "
      label: "Cluster ID"
      type: "string"
      required: true
      default: ""
    - variable: kvdb
      description: "Key-value database, accessibe to all nodes in PX cluster (Ex: 'etcd://10.0.0.42:4001')"
      label: "Key-Value Database"
      type: "string"
      required: true
      default: ""
    - variable: use_disks
      description: "Cmdline args for disks to use. Ex: '-a' for all available, or '-s /dev/sdX' for each individual disk"
      label: "Use Disks"
      type: "string"
      required: true
      default: "-s /dev/xvdb"
    - variable: header_dir
      description: "Directory where kernel headers can be found.  Default is '/usr/src'.  For CoreOS use '/lib/modules'"
      label: "Headers Directory"
      type: "string"
      required: true
      default: "/usr/src"
