version: '2'
services:
  web:
    image: drupal
    ports:
    - ${public_port}:80
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${database}
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
      MYSQL_USER: ${mysql_newusr}
      MYSQL_PASSWORD: ${mysql_newusr_password}
