.catalog:
  name: Chronos
  version: v1
  minimum_rancher_version: v1.0.0
  maximum_rancher_version: v1.2.0-pre3
  description: |
    Distributed, fault-tolerant cron
  questions:
  - variable: CHRONOS_HTTP_PORT
    description: Port to expose Chronos on.
    label: Chronos Port
    required: true
    type: int
    default: 8080
chronos:
  scale: 1
  health_check:
    port: ${CHRONOS_HTTP_PORT}
    interval: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
    request_line: '/'
    response_timeout: 2000
