name: CloudFlare DNS
description: |
  Rancher External DNS service powered by CloudFlare
version: v0.6.0-rancher2
category: External DNS
labels:
  io.rancher.orchestration.supported: 'cattle,mesos,swarm,kubernetes'
