name: Apache Zookeeper
description: |
  Zookeeper cluster
version: 3.4.10-rancher1
category: Clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
projectURL: https://github.com/rawmind0/alpine-zk
license: 
