.catalog:
  name: "Zammad"
  version: "1.2"
  description: "Zammad is a web based open source helpdesk/customer support system"
  uuid: zammad-1
  minimum_rancher_version: v1.2.0
  questions:

elasticsearch:
  scale: 1
  start_on_create: true
nginx:
  scale: 1
  start_on_create: true
postgresql:
  scale: 1
  start_on_create: true
zammad:
  scale: 1
  start_on_create: true
zammad-scheduler:
  scale: 1
  start_on_create: true
zammad-railsserver:
  scale: 1
  start_on_create: true
zammad-websocket:
  scale: 1
  start_on_create: true
