.catalog:
  version: v1.13.0-beta.1
  minimum_rancher_version: 1.2.2
  questions:
  - variable: MANAGER_SCALE
    label: Number of Managers
    description: Desired number of managers to participating in service orchestration. This dictates host resilience.
    required: true
    default: 3
    type: enum
    options:
    - 1
    - 3
    - 5
    - 7
    - 9
swarmkit-mon:
  health_check:
    request_line: GET /ping HTTP/1.0
    port: 2378
    interval: 15000
    response_timeout: 10000
    healthy_threshold: 1
    unhealthy_threshold: 2
