version: '2'

catalog:

  name: bitbucket
  version: 0.0.1
  description: Git Server
  questions:
    - variable: BITBUCKET_PORT
      label: Port
      default: 80
      required: true
      type: int

services:

  bitbucket:
    scale: 1
    start_on_create: true

  bitbucket-data:
    scale: 1
    start_on_create: true

