name: Infoblox DNS
description: |
  Rancher External DNS service powered by Infoblox
version:  v0.2.0
category: External DNS
labels:
  io.rancher.orchestration.supported: 'cattle,mesos,swarm,kubernetes'
