name: Logentries
description: |
  Forward all your Docker logs to logentries, like a breeze.
version: "0.2.1"
category: Logging
maintainer: "Nick Haynes <nick.t.haynes@gmail.com>"
license: The MIT License
