name: DNS Update (RFC2136)
description: |
  Rancher External DNS service powered by any RFC2136 compatible DNS
version: v0.7.2-rancher1
category: External DNS
labels:
  io.rancher.orchestration.supported: 'cattle,mesos,swarm,kubernetes'
